name: Deploy Natural Bathing Admin to Hpanel

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Natural Bathing Admin to Hpanel

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/u376682195/domains/naturalbathingpab.com/
            git clone https://github.com/ahmakbardev/naturalbathing_admin.git
            chmod +x ~/bin/composer
            echo "export PATH=$HOME/bin:$PATH" >> ~/.bash_profile
            source ~/.bash_profile
            which composer
            composer --version
            cd /home/u376682195/domains/naturalbathingpab.com/naturalbathing_admin/
            cp .env.example .env
            git pull origin develop
            composer update
            php artisan key:generate
            ln -s /home/u376682195/domains/naturalbathingpab.com/naturalbathing_admin/public /home/u376682195/domains/naturalbathingpab.com/public_html/admin
